### ISSUE TITLE
Rails 3.2.1 undefined method `generators' 

### ISSUE THREAD

**Issue by tatiC** [activeadmin/inherited_resources#209]
Hi all,

ruby 1.9.2p180
Rails 3.2.1

When i run rails generate scaffold Film name:string

i receive:
configuration.rb:85:in `method_missing': undefined method`generators' for #<Rails::Railtie::Configuration

if i delete inherited resources from my Gemfile the error disappears...

Also tried in my application.rb: 
config.app_generators.scaffold_controller = :scaffold_controller

thanks!

**Comment by maxiperezunlam** [comment]
+1 

This is my backtrace

```
Uncaught exception: undefined method `generators' for #<Rails::Railtie::Configuration:0x000000045aba00>
    /usr/local/rvm/gems/ruby-1.9.3-p125@mongoblog1.9.3/gems/railties-3.2.1/lib/rails/railtie/configuration.rb:85:in `method_missing'
    /usr/local/rvm/gems/ruby-1.9.3-p125@mongoblog1.9.3/gems/mongoid-2.0.0.beta.19/lib/mongoid/railtie.rb:13:in `<class:Railtie>'
    /usr/local/rvm/gems/ruby-1.9.3-p125@mongoblog1.9.3/gems/mongoid-2.0.0.beta.19/lib/mongoid/railtie.rb:11:in `<module:Mongoid>'
    /usr/local/rvm/gems/ruby-1.9.3-p125@mongoblog1.9.3/gems/mongoid-2.0.0.beta.19/lib/mongoid/railtie.rb:10:in `<module:Rails>'
    /usr/local/rvm/gems/ruby-1.9.3-p125@mongoblog1.9.3/gems/mongoid-2.0.0.beta.19/lib/mongoid/railtie.rb:9:in `<top (required)>'
    /usr/local/rvm/gems/ruby-1.9.3-p125@mongoblog1.9.3/gems/mongoid-2.0.0.beta.19/lib/mongoid.rb:89:in `require'
    /usr/local/rvm/gems/ruby-1.9.3-p125@mongoblog1.9.3/gems/mongoid-2.0.0.beta.19/lib/mongoid.rb:89:in `<top (required)>'
    /usr/local/rvm/rubies/ruby-1.9.3-p125/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    /usr/local/rvm/rubies/ruby-1.9.3-p125/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    /usr/local/rvm/gems/ruby-1.9.3-p125@global/gems/bundler-1.0.22/lib/bundler/runtime.rb:68:in `block (2 levels) in require'
    /usr/local/rvm/gems/ruby-1.9.3-p125@global/gems/bundler-1.0.22/lib/bundler/runtime.rb:66:in `each'
    /usr/local/rvm/gems/ruby-1.9.3-p125@global/gems/bundler-1.0.22/lib/bundler/runtime.rb:66:in `block in require'
    /usr/local/rvm/gems/ruby-1.9.3-p125@global/gems/bundler-1.0.22/lib/bundler/runtime.rb:55:in `each'
    /usr/local/rvm/gems/ruby-1.9.3-p125@global/gems/bundler-1.0.22/lib/bundler/runtime.rb:55:in `require'
    /usr/local/rvm/gems/ruby-1.9.3-p125@global/gems/bundler-1.0.22/lib/bundler.rb:122:in `require'
    /home/maximiliano/Proyectos/mongoblog/config/application.rb:13:in `<top (required)>'
    /usr/local/rvm/gems/ruby-1.9.3-p125@mongoblog1.9.3/gems/railties-3.2.1/lib/rails/commands.rb:53:in `require'
    /usr/local/rvm/gems/ruby-1.9.3-p125@mongoblog1.9.3/gems/railties-3.2.1/lib/rails/commands.rb:53:in `block in <top (required)>'
    /usr/local/rvm/gems/ruby-1.9.3-p125@mongoblog1.9.3/gems/railties-3.2.1/lib/rails/commands.rb:50:in `tap'
    /usr/local/rvm/gems/ruby-1.9.3-p125@mongoblog1.9.3/gems/railties-3.2.1/lib/rails/commands.rb:50:in `<top (required)>'
    /home/maximiliano/Proyectos/mongoblog/script/rails:6:in `require'
    /home/maximiliano/Proyectos/mongoblog/script/rails:6:in `<top (required)>'
```

**Comment by carlosantoniodasilva** [comment]
We're releasing a new version of IR, please try it after the release and let us know if that worked. Thanks

**Comment by rafaelfranca** [comment]
@tatiC could you try with this new release? Thanks

**Comment by tatiC** [comment]
@carlosantoniodasilva and @rafaelfranca just tried with the new release (1.3.1)
It's working now! :) Thanks! 
Sorry about the delay ;)

**Comment by carlosantoniodasilva** [comment]
Great! :)
