### ISSUE TITLE
rails4 and IR

### ISSUE THREAD

**Issue by alec-c4** [activeadmin/inherited_resources#280]
Hi,
I've tried to use IR in rails4 app, but my code

```
class WorkspacesController < InheritedResources::Base

  private

  def permitted_params
    params.permit(:workspace => [:name, :owner_id])
  end
end
```

raises ActiveModel::ForbiddenAttributesError exception. Whats wrong with this code?

**Comment by alec-c4** [comment]
There are workaround - http://blog.josemarluedke.com/posts/inherited-resources-with-rails-4-and-strong-parameters

**Comment by joelmoss** [comment]
Have you guys tried with IR 1.4, as that has support for Rails4 and strong params?

**Comment by alec-c4** [comment]
There are some problems with IR 1.4 :)

```
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    inherited_resources (>= 1.4.0) ruby depends on
      railties (~> 3.1) ruby

    rails (= 4.0.0.rc1) ruby depends on
      railties (4.0.0.rc1)
```

**Comment by joelmoss** [comment]
Please use master branch for now, which should work fine...

```
gem 'inherited_resources', github: 'josevalim/inherited_resources'
```

**Comment by alec-c4** [comment]
not working

``` ruby

class ProjectsController < InheritedResources::Base
  respond_to :html, :xml, :json
  before_filter :authenticate_user!


  private

  def permitted_params
    params.permit(:name, :description, :workspace_id)
  end

end
```

In logs i see

```
Started POST "/projects" for 127.0.0.1 at 2013-05-11 16:45:47 +0400
Processing by ProjectsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"rgwdDlsIgqOnViGvi23sSYozRh1e2LwJ9GBNkhjjFBc=", "project"=>{"name"=>"weewrw", "description"=>"werwer", "workspace_id"=>"5"}, "commit"=>"Create Project"}
DEPRECATION WARNING: Relation#first with finder options is deprecated. Please build a scope and then call #first on it instead. (called from load at /Users/alec/.rvm/gems/ruby-2.0.0-p0@progressor/bin/unicorn_rails:23)
  User Load (0.6ms)  SELECT "users".* FROM "users" WHERE "users"."id" = 1 ORDER BY "users"."id" ASC LIMIT 1
Unpermitted parameters: utf8, authenticity_token, project, commit
   (0.2ms)  BEGIN
   (0.2ms)  ROLLBACK
DEPRECATION WARNING: Relation#all is deprecated. If you want to eager-load a relation, you can call #load (e.g. `Post.where(published: true).load`). If you want to get an array of records from a relation, you can call #to_a (e.g. `Post.where(published: true).to_a`). (called from block in _app_views_projects__form_html_slim___2193259297966455815_70262466174460 at /Users/alec/Documents/Projects/RubyApps/progressor/app/views/projects/_form.html.slim:7)
```

**Comment by joelmoss** [comment]
You need to use: `params.permit(:project => [:name, :description, :workspace_id])`

**Comment by alec-c4** [comment]
works perfectly :) :thumbsup: :heart: :dancers:

**Comment by alec-c4** [comment]
One more problem with overwriting actions:

``` ruby
  def create
    @project = Project.new(permitted_params)
    @project.workspace = Workspace.first
    create!
  end
```

causes error

```
Started POST "/projects" for 127.0.0.1 at 2013-05-11 17:27:04 +0400
Processing by ProjectsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"rgwdDlsIgqOnViGvi23sSYozRh1e2LwJ9GBNkhjjFBc=", "project"=>{"name"=>"ytrrty", "description"=>"rtyrtytr", "workspace_id"=>""}, "commit"=>"Create Project"}
DEPRECATION WARNING: Relation#first with finder options is deprecated. Please build a scope and then call #first on it instead. (called from load at /Users/alec/.rvm/gems/ruby-2.0.0-p0@progressor/bin/unicorn_rails:23)
  User Load (0.5ms)  SELECT "users".* FROM "users" WHERE "users"."id" = 1 ORDER BY "users"."id" ASC LIMIT 1
Unpermitted parameters: utf8, authenticity_token, commit
Completed 500 Internal Server Error in 4ms
** [Bugsnag] No API key configured, couldn't notify

ActiveRecord::UnknownAttributeError - unknown attribute: project:
  (gem) activerecord-4.0.0.rc1/lib/active_record/attribute_assignment.rb:47:in `rescue in _assign_attribute'
  (gem) activerecord-4.0.0.rc1/lib/active_record/attribute_assignment.rb:42:in `_assign_attribute'
  (gem) activerecord-4.0.0.rc1/lib/active_record/attribute_assignment.rb:53:in `block in assign_nested_parameter_attributes'
```

**Comment by alec-c4** [comment]
@joelmoss could you check?

**Comment by joelmoss** [comment]
Check your workspace model, as this is all about using Strong Params correctly, and nothing to do with IR.

**Comment by alec-c4** [comment]
@joelmoss maybe you mean project model? because i'm operating with project. It looks like there are problems with following string

``` ruby
@project = Project.new(permitted_params)
```

because 

``` ruby
  def create
    create!
  end
```

works fine. I cannot get params hash from custom action :(

**Comment by tonyc** [comment]
Running into the same problem with the "new" action as well. It's complaining about params[:utf8], params[:authenticity_token] etc... am I missing something obvious?

**Comment by mcansky** [comment]
update ?

**Comment by rafaelgoulart** [comment]
@tonyc Same here.

**Comment by thromera** [comment]
Up

**Comment by radwas88** [comment]
Hi Guys, 

I have a problem with activeadmin and inherited resources. When I try to install activeadmin I get below issue:
`Bundler could not find compatible versions for gem "inherited_resources":
  In Gemfile:
    activeadmin (>= 0) ruby depends on
      inherited_resources (~> 1.4.1) ruby
    inherited_resources (1.3.1)`

My environment versions are:
- rails 4.1.1
- ruby 2.0.0p247
  In Gemfile I have following lines for gems:
  gem 'activeadmin', github: 'gregbell/active_admin', branch: 'rails4'
  gem 'inherited_resources', github: 'josevalim/inherited_resources'

If anyone could let me know what to do it would be great. I've tried various solutions and any of them helpd.

Regards
