### ISSUE TITLE
Circular dependency on heroku

### ISSUE THREAD

**Issue by MicrowaveDev** [activeadmin/inherited_resources#399]
On the local machine gem works great, but when you run rails app on heroku this error:

```
app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:492:in `load_missing_constant': Circular dependency detected while autoloading constant InheritedResources::Base (RuntimeError)
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:184:in `const_missing'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/bundler/gems/inherited_resources-d43bd6d1adfd/lib/inherited_resources.rb:40:in `inherit_resources'
app[web.1]:     from /app/app/controllers/application_controller.rb:11:in `<class:ApplicationController>'
app[web.1]:     from /app/app/controllers/application_controller.rb:1:in `<top (required)>'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:360:in `require_or_load'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:494:in `load_missing_constant'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:184:in `const_missing'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/bundler/gems/inherited_resources-d43bd6d1adfd/app/controllers/inherited_resources/base.rb:11:in `<module:InheritedResources>'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/bundler/gems/inherited_resources-d43bd6d1adfd/app/controllers/inherited_resources/base.rb:1:in `<top (required)>'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:360:in `require_or_load'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:317:in `depend_on'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:233:in `require_dependency'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/engine.rb:471:in `each'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/engine.rb:471:in `block in eager_load!'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/engine.rb:469:in `eager_load!'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/engine.rb:469:in `each'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/engine.rb:346:in `eager_load!'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/application/finisher.rb:56:in `each'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `instance_exec'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `run'
app[web.1]:     from /app/vendor/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
app[web.1]:     from /app/vendor/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:55:in `block in run_initializers'
app[web.1]:     from /app/vendor/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
app[web.1]:     from /app/vendor/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `call'
app[web.1]:     from /app/vendor/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
app[web.1]:     from /app/vendor/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
app[web.1]:     from /app/vendor/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each'
app[web.1]:     from /app/vendor/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
app[web.1]:     from /app/config/environment.rb:5:in `<top (required)>'
app[web.1]:     from /app/vendor/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:54:in `run_initializers'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/application.rb:352:in `initialize!'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
app[web.1]:     from /app/config.ru:in `new'
app[web.1]:     from /app/config.ru:in `<main>'
app[web.1]:     from /app/config.ru:3:in `block in <main>'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:272:in `start'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/commands/server.rb:61:in `app'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:80:in `block in server'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/commands/server.rb:80:in `start'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:75:in `server'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
app[web.1]:     from bin/rails:8:in `require'
app[web.1]:     from bin/rails:8:in `<main>'
app[web.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
heroku[web.1]: Process exited with status 1
heroku[web.1]: State changed from starting to crashed
```

Controller:

```
class ApplicationController < ActionController::Base

  include ActionController::MimeResponds
  include ActionController::Helpers
  include ActionController::Cookies
  include ActionController::ImplicitRender
  respond_to :json, :html
  protect_from_forgery with: :exception

  inherit_resources
  actions :all

end
```

Gemfile:

```
source 'https://rubygems.org'
ruby '2.2.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.1'
# Use sqlite3 as the database for Active Record
#gem 'sqlite3'

gem 'mongoid', '~> 4.0.0'
gem 'moped', github: 'mongoid/moped'
gem 'simple_enum', '~> 2.0.0' , require: 'simple_enum/mongoid'


# Use SCSS for stylesheets
gem 'bootstrap-sass', '~> 3.3.3'
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
#gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

gem 'inherited_resources', github: 'josevalim/inherited_resources', branch: 'master'

gem 'oj'
gem 'rabl'
gem 'slim-rails'

gem 'simple_form'

gem 'select2-rails'

gem 'rails_admin', github: 'pencilcheck/rails_admin', branch: 'master'

gem 'cancan'

gem 'bcrypt-ruby', :require => 'bcrypt'

# gem to enable all heroku platform features
# See https://devcenter.heroku.com/articles/rails-integration-gems for more information.
gem 'rails_12factor'
```

I really like your gem, and I would hate to give it up due to the fact that it is impossible to run on the server.
I was looking for the cause of this error, and I think that the problem may be in this:
https://groups.google.com/forum/#!topic/ruby-grape/zu5bHWd_t94

**Comment by rafaelfranca** [comment]
It is because you are including `inherit_resources` at the `ApplicationController` and you should not since `InheritResources::Base` inherit from `ApplicationController`.
