### ISSUE TITLE
Problems with Rails 5

### ISSUE THREAD

**Issue by hron84** [activeadmin/inherited_resources#414]
It seems like Inherited Resources have problems with Rails 5. No hurry, I just leave this here to inform you about it.

```
There was an error while trying to load the gem 'inherited_resources'.
Gem Load Error is: uninitialized constant ActionController::Responder
Backtrace for gem load error is:
/home/hron/.rvm/gems/ruby-2.3.0@compass/gems/inherited_resources-1.3.1/lib/inherited_resources/responder.rb:2:in `<module:InheritedResources>'
/home/hron/.rvm/gems/ruby-2.3.0@compass/gems/inherited_resources-1.3.1/lib/inherited_resources/responder.rb:1:in `<top (required)>'
/home/hron/.rvm/gems/ruby-2.3.0@compass/gems/inherited_resources-1.3.1/lib/inherited_resources.rb:4:in `<top (required)>'
/home/hron/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `require'
/home/hron/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
/home/hron/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
/home/hron/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
/home/hron/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
/home/hron/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
/home/hron/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
/stuffz/projects/playground/rails/compass/config/application.rb:17:in `<top (required)>'
/home/hron/.rvm/gems/ruby-2.3.0@compass/gems/spring-1.7.2/lib/spring/application.rb:82:in `require'
/home/hron/.rvm/gems/ruby-2.3.0@compass/gems/spring-1.7.2/lib/spring/application.rb:82:in `preload'
/home/hron/.rvm/gems/ruby-2.3.0@compass/gems/spring-1.7.2/lib/spring/application.rb:143:in `serve'
/home/hron/.rvm/gems/ruby-2.3.0@compass/gems/spring-1.7.2/lib/spring/application.rb:131:in `block in run'
/home/hron/.rvm/gems/ruby-2.3.0@compass/gems/spring-1.7.2/lib/spring/application.rb:125:in `loop'
/home/hron/.rvm/gems/ruby-2.3.0@compass/gems/spring-1.7.2/lib/spring/application.rb:125:in `run'
/home/hron/.rvm/gems/ruby-2.3.0@compass/gems/spring-1.7.2/lib/spring/application/boot.rb:19:in `<top (required)>'
/home/hron/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/hron/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
-e:1:in `<main>'
Bundler Error Backtrace:
 (Bundler::GemRequireError)
    from /home/hron/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:85:in `block (2 levels) in require'
    from /home/hron/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
    from /home/hron/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
    from /home/hron/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
    from /home/hron/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
    from /home/hron/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
    from /stuffz/projects/playground/rails/compass/config/application.rb:17:in `<top (required)>'
    from /home/hron/.rvm/gems/ruby-2.3.0@compass/gems/spring-1.7.2/lib/spring/application.rb:82:in `require'
    from /home/hron/.rvm/gems/ruby-2.3.0@compass/gems/spring-1.7.2/lib/spring/application.rb:82:in `preload'
    from /home/hron/.rvm/gems/ruby-2.3.0@compass/gems/spring-1.7.2/lib/spring/application.rb:143:in `serve'
    from /home/hron/.rvm/gems/ruby-2.3.0@compass/gems/spring-1.7.2/lib/spring/application.rb:131:in `block in run'
    from /home/hron/.rvm/gems/ruby-2.3.0@compass/gems/spring-1.7.2/lib/spring/application.rb:125:in `loop'
    from /home/hron/.rvm/gems/ruby-2.3.0@compass/gems/spring-1.7.2/lib/spring/application.rb:125:in `run'
    from /home/hron/.rvm/gems/ruby-2.3.0@compass/gems/spring-1.7.2/lib/spring/application/boot.rb:19:in `<top (required)>'
    from /home/hron/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/hron/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from -e:1:in `<main>'
```

**Comment by rafaelfranca** [comment]
Oh, This is using inherited_resources 1.3.1 and it doesn't support Rails 5. Make sure you are using the master branch,

**Comment by hron84** [comment]
@rafaelfranca Master has a R5 compatibility? When do you expect it will be released?
