### ISSUE TITLE
Breaking Capybara Rails Load

### ISSUE THREAD

**Issue by gmoeck** [activeadmin/inherited_resources#58]
I get the following error when including InheritedResources in my rails 3 app, and running any feature through cucumber. It does seem to function fine when run in the web server. I'll keep poking at it, but I wanted to post the issue.

```
wrong number of arguments (1 for 2) (ArgumentError)
/Users/gmoeck/.rvm/gems/ruby-1.8.7-p248/gems/rack-1.1.0/lib/rack/builder.rb:54:in `initialize'
/Users/gmoeck/.rvm/gems/ruby-1.8.7-p248/gems/rack-1.1.0/lib/rack/builder.rb:54:in `new'
/Users/gmoeck/.rvm/gems/ruby-1.8.7-p248/gems/rack-1.1.0/lib/rack/builder.rb:54
/Users/gmoeck/.rvm/gems/ruby-1.8.7-p248/gems/rack-1.1.0/lib/rack/builder.rb:73:in `call'
/Users/gmoeck/.rvm/gems/ruby-1.8.7-p248/gems/rack-1.1.0/lib/rack/builder.rb:73:in `to_app'
/Users/gmoeck/.rvm/gems/ruby-1.8.7-p248/bundler/gems/capybara-f47214fa54f8dae1ca782e48ee86d54cdb2dc0b3-master/lib/capybara/rails.rb:4:in `inject'
/Users/gmoeck/.rvm/gems/ruby-1.8.7-p248/gems/rack-1.1.0/lib/rack/builder.rb:73:in `each'
/Users/gmoeck/.rvm/gems/ruby-1.8.7-p248/gems/rack-1.1.0/lib/rack/builder.rb:73:in `inject'
/Users/gmoeck/.rvm/gems/ruby-1.8.7-p248/gems/rack-1.1.0/lib/rack/builder.rb:73:in `to_app'
/Users/gmoeck/.rvm/gems/ruby-1.8.7-p248/gems/rack-1.1.0/lib/rack/builder.rb:63:in `map'
/Users/gmoeck/.rvm/gems/ruby-1.8.7-p248/gems/rack-1.1.0/lib/rack/builder.rb:66:in `map'
/Users/gmoeck/.rvm/gems/ruby-1.8.7-p248/bundler/gems/capybara-f47214fa54f8dae1ca782e48ee86d54cdb2dc0b3-master/lib/capybara/rails.rb:5
/Users/gmoeck/.rvm/gems/ruby-1.8.7-p248/gems/rack-1.1.0/lib/rack/builder.rb:46:in `instance_eval'
/Users/gmoeck/.rvm/gems/ruby-1.8.7-p248/gems/rack-1.1.0/lib/rack/builder.rb:46:in `initialize'
/Users/gmoeck/.rvm/gems/ruby-1.8.7-p248/bundler/gems/capybara-f47214fa54f8dae1ca782e48ee86d54cdb2dc0b3-master/lib/capybara/rails.rb:4:in `new'
/Users/gmoeck/.rvm/gems/ruby-1.8.7-p248/bundler/gems/capybara-f47214fa54f8dae1ca782e48ee86d54cdb2dc0b3-master/lib/capybara/rails.rb:4
/Users/gmoeck/.rvm/gems/ruby-1.8.7-p248/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `require'
/Users/gmoeck/.rvm/gems/ruby-1.8.7-p248/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `require'
/Users/gmoeck/.rvm/gems/ruby-1.8.7-p248/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:200:in `load_dependency'
/Users/gmoeck/.rvm/gems/ruby-1.8.7-p248/gems/activesupport-3.0.0.beta4/lib/active_support/dependencies.rb:212:in `require'
/Users/gmoeck/Rails/warehouse_manager/features/support/env.rb:15
/Users/gmoeck/.rvm/rubies/ruby-1.8.7-p248/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/Users/gmoeck/.rvm/rubies/ruby-1.8.7-p248/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
/Users/gmoeck/.rvm/gems/ruby-1.8.7-p248/gems/cucumber-0.8.3/bin/../lib/cucumber/rb_support/rb_language.rb:141:in `load_code_file'
/Users/gmoeck/.rvm/gems/ruby-1.8.7-p248/gems/cucumber-0.8.3/bin/../lib/cucumber/step_mother.rb:84:in `load_code_file'
/Users/gmoeck/.rvm/gems/ruby-1.8.7-p248/gems/cucumber-0.8.3/bin/../lib/cucumber/step_mother.rb:76:in `load_code_files'
/Users/gmoeck/.rvm/gems/ruby-1.8.7-p248/gems/cucumber-0.8.3/bin/../lib/cucumber/step_mother.rb:75:in `each'
/Users/gmoeck/.rvm/gems/ruby-1.8.7-p248/gems/cucumber-0.8.3/bin/../lib/cucumber/step_mother.rb:75:in `load_code_files'
/Users/gmoeck/.rvm/gems/ruby-1.8.7-p248/gems/cucumber-0.8.3/bin/../lib/cucumber/cli/main.rb:53:in `execute!'
/Users/gmoeck/.rvm/gems/ruby-1.8.7-p248/gems/cucumber-0.8.3/bin/../lib/cucumber/cli/main.rb:25:in `execute'
/Users/gmoeck/.rvm/gems/ruby-1.8.7-p248/gems/cucumber-0.8.3/bin/cucumber:8
rake aborted!
```

**Comment by gmoeck** [comment]
I was running on edge capybara, when I switched to the gem, it seems to fix the problem. Going to see if I can spot what changes made the issue occur.

**Comment by gmoeck** [comment]
For whatever reason, when they changed
    ActionDispatch::Static
to
    use ActionDispatch::Static

It gives that error. Likely a capybara issue, not an inherited_resources issue. Not sure what the difference is though, so I've posted a link back to the issue I put here.
